version: '2'

services:
  app:
    image: 'spring-app:latest'
    build:
      context: .
    container_name: task
    links:
      - db
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=elephant
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elephant
      - POSTGRES_DB=taskdb
    expose:
      - 5432